embeddings: True
epochs: 4000
batch_size: 32
validation_split: 0.3
test_split: 0.15
project_name: DoubleModel_Predicates_Tests
run_name: DoubleModel_TestePT_2k_3_5
train_new: False
train_model: False
load_data_train: True
load_data_test: False
save_data_train: False
save_data_test: True
data_file: Data/EN_Train_Embeddings_Predicate_10k.pt
targets_file: Data/EN_Train_Embeddings_Predicate_10k.pkl
#model_file: Models/EN_Train_Embeddings_SubObj_10k.pt
model_file: Models/EN_Train_Embeddings_Predicate_10k.pt
#test_data_file: Data/EN_Test_Embeddings_SubObj.pt
#test_targets_file: Data/EN_Test_Embeddings_SubObj_Targets.pkl
#test_indexes_file: Data/EN_Test_Embeddings_SubObj_Indexes.pkl
test_data_file: Data/PT_Test_Embeddings_Predicate_2k.pt
test_targets_file: Data/PT_Test_Embeddings_Predicate_Targets_2k.pkl
test_indexes_file: Data/PT_Test_Embeddings_Predicate_Indexes_2k.pkl