embeddings: True
epochs: 5000
batch_size: 32
validation_split: 0.3
test_split: 0.15
project_name: SOMD2025_withBinary
run_name: SOMD2025_run_
train_new: True
train_model: True
load_data_train: False
load_data_test: False
save_data_train: True
save_data_test: True
data_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_Train_800_withBinary.pt
targets_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TrainTargets_8002_withBinary.pkl
#model_file: Models/EN_Train_Embeddings_Predicate_10k.pt
model_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Models/SOMD_8002_withBinary.pt
#test_data_file: Data/EN_Test_Embeddings_Predicate.pt
#test_targets_file: Data/EN_Test_Embeddings_Predicate_Targets.pkl
#test_indexes_file: Data/EN_Test_Embeddings_Predicate_Indexes.pkl
test_data_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_Test_3002_withBinary.pt
test_targets_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TestTargets_3002_withBinary.pkl
test_indexes_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TestIndexes_3002_withBinary.pkl