embeddings: True
epochs: 6000
batch_size: 32
validation_split: 0.3
test_split: 0.15
project_name: SOMD2025_TestWeighted
run_name: SOMD2025_Test_run_
train_new: True
train_model: True
load_data_train: True
load_data_test: True
save_data_train: False
save_data_test: False
data_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_Train_800.pt
targets_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TrainTargets_800.pkl
#model_file: Models/EN_Train_Embeddings_Predicate_10k.pt
model_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Models/SOMD_800.pt
#test_data_file: Data/EN_Test_Embeddings_Predicate.pt
#test_targets_file: Data/EN_Test_Embeddings_Predicate_Targets.pkl
#test_indexes_file: Data/EN_Test_Embeddings_Predicate_Indexes.pkl
test_data_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_Test_300.pt
test_targets_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TestTargets_300.pkl
test_indexes_file: /home/grsilva/GraphBuilderAPI_v2/ML_Only/Data/SOMD_TestIndexes_300.pkl