folder: Data_to_process/Task1/Merged
uri: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#
#language: pt_core_news_sm
language: en_core_web_sm
graph_name: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#
connection: http://hlt.ieeta.pt:8890/sparql
in_memory: False
save_file: TTLs/Subtask1_LinkPrediction
extra_connections:
  connections: [softwareMention]
  #connections: [wikinerGrammarFeats, wikinerEntity, entityPresent]