folder: Data_to_process/SOMD2025/Merged
uri: http://www.ieeta-bit.pt/SOMD2025_v3#
#language: pt_core_news_sm
language: en_core_web_sm
graph_name: http://www.ieeta-bit.pt/SOMD2025_v3#
connection: http://hlt.ieeta.pt:8890/sparql
in_memory: False
save_file: ML_Only/TTLs/SOMD2025
extra_connections:
  connections: [OIE_tags]