folder: Data_to_process/Task1/Merged_Even_Shorter
uri: http://www.ieeta-bit.pt/Subtask1_PreProcess_Short#
#language: pt_core_news_sm
language: en_core_web_sm
graph_name: http://www.ieeta-bit.pt/Subtask1_PreProcess_Short#
connection: http://hlt.ieeta.pt:8890/sparql
in_memory: True
save_file: TTLs/Subtask1_PreProcess
extra_connections:
  connections: [softwareMention]
  #connections: [wikinerGrammarFeats, wikinerEntity, entityPresent]