connection:
  - connection_uri: http://hlt.ieeta.pt:8890/sparql
    graph_name: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#
    base_uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#
enable_wandb:
  True
nodes:
#  - name: edge
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#edge
#    edges_source: []
#    edges: []
#    edges_target: []
#    edges_uri: []
#    attributes: []
#  - name: pos
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#pos
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: poscoarse
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#poscoarse
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_aspect
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_aspect
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_case
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_case
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_definite
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_definite
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_degree
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_degree
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_foreign
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_foreign
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_gender
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_gender
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_mood
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_mood
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_number
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_number
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_numtype
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_numtype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_person
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_person
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_polarity
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_polarity
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_poss
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_poss
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_prontype
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_prontype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_punctside
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_punctside
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_puncttype
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_puncttype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_tense
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_tense
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_verbform
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_verbform
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_conjtype
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_conjtype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: feat_foreign
#    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#feat_foreign
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
  - name: word
    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#Word
    edges_source: [word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word]
    edges: [depGraph, head, previousWord, fromSentence, nextWord, pos, edge, feat_aspect, feat_case, feat_conjtype, feat_definite, feat_degree, feat_foreign, feat_gender, feat_mood, feat_number, feat_numtype, feat_person, feat_polarity, feat_poss, feat_prontype, feat_punctside, feat_puncttype, feat_tense, feat_verbform]
    edges_target: [word, word, word, sentence, word, pos, edge, feat_aspect, feat_case, feat_conjtype, feat_definite, feat_degree, feat_foreign, feat_gender, feat_mood, feat_number, feat_numtype, feat_person, feat_polarity, feat_poss, feat_prontype, feat_punctside, feat_puncttype, feat_tense, feat_verbform]
    edges_uri: [http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#depGraph, http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#head, http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#previousWord, http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#fromSentence]
    attributes: [lemma, word]
  - name: sentence
    uri: http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#Sentence
#    edges_source: [sentence, sentence]
#    edges: [nextSentence, depGraph]
#    edges_target: [sentence, word]
#    edges_uri: [http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#nextSentence, http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#depGraph]
    edges_source: [sentence]
    edges: [nextSentence]
    edges_target: [sentence]
    edges_uri: [http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#nextSentence]
    attributes: [senttext]
target:
  - node: word
    name: [softwareMention]
    uri: [http://www.ieeta-bit.pt/Subtask1_ObjectProperties_v2#softwareMention]
    balancing: False