connection:
  - connection_uri: http://hlt.ieeta.pt:8890/sparql
    graph_name: http://www.ieeta-bit.pt/Conll_Coref_train#
    base_uri: http://www.ieeta-bit.pt/Conll_Coref_train#
    graph_name_test: http://www.ieeta-bit.pt/Conll_Coref_train#
    base_uri_test: http://www.ieeta-bit.pt/Conll_Coref_train#
enable_wandb:
  True
nodes:
#  - name: edge
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#edge
#    edges_source: []
#    edges: []
#    edges_target: []
#    edges_uri: []
#    attributes: []
#  - name: pos
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#pos
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: poscoarse
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#poscoarse
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: aspect
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#aspect
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: case
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#case
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: definite
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#definite
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: degree
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#degree
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: foreign
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#foreign
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: gender
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#gender
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: mood
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#mood
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: number
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#number
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: numtype
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#numtype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: person
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#person
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: polarity
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#polarity
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: poss
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#poss
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: prontype
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#prontype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: punctside
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#punctside
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: puncttype
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#puncttype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: tense
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#tense
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: verbform
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#verbform
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: conjtype
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#conjtype
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: foreign
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#foreign
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
#  - name: coReference
#    uri: http://www.ieeta-bit.pt/Conll_Coref_train#coReference
#    edges_source: [ ]
#    edges: [ ]
#    edges_target: [ ]
#    edges_uri: [ ]
#    attributes: [ ]
  - name: word
    uri: http://www.ieeta-bit.pt/Conll_Coref_train#Word
    edges_source: [word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word, word]
    edges: [coReference, depGraph, head, previousWord, fromSentence, nextWord, poscoarse, pos, edge, aspect, case, conjtype, definite, degree, gender, mood, number, numtype, person, polarity, poss, prontype, punctside, puncttype, tense, verbform]
    edges_target: [word, word, word, word, sentence, word, poscoarse, pos, edge, aspect, case, conjtype, definite, degree, gender, mood, number, numtype, person, polarity, poss, prontype, punctside, puncttype, tense, verbform]
    edges_uri: [http://www.ieeta-bit.pt/Conll_Coref_train#coReference, http://www.ieeta-bit.pt/Conll_Coref_train#depGraph, http://www.ieeta-bit.pt/Conll_Coref_train#head, http://www.ieeta-bit.pt/Conll_Coref_train#previousWord, http://www.ieeta-bit.pt/Conll_Coref_train#fromSentence, http://www.ieeta-bit.pt/Conll_Coref_train#poscoarse, http://www.ieeta-bit.pt/Conll_Coref_train#pos, http://www.ieeta-bit.pt/Conll_Coref_train#edge, http://www.ieeta-bit.pt/Conll_Coref_train#aspect, http://www.ieeta-bit.pt/Conll_Coref_train#case, http://www.ieeta-bit.pt/Conll_Coref_train#conjtype, http://www.ieeta-bit.pt/Conll_Coref_train#definite, http://www.ieeta-bit.pt/Conll_Coref_train#degree, http://www.ieeta-bit.pt/Conll_Coref_train#foreign, http://www.ieeta-bit.pt/Conll_Coref_train#gender, http://www.ieeta-bit.pt/Conll_Coref_train#mood, http://www.ieeta-bit.pt/Conll_Coref_train#number, http://www.ieeta-bit.pt/Conll_Coref_train#numtype, http://www.ieeta-bit.pt/Conll_Coref_train#person, http://www.ieeta-bit.pt/Conll_Coref_train#polarity, http://www.ieeta-bit.pt/Conll_Coref_train#poss, http://www.ieeta-bit.pt/Conll_Coref_train#prontype, http://www.ieeta-bit.pt/Conll_Coref_train#punctside, http://www.ieeta-bit.pt/Conll_Coref_train#puncttype, http://www.ieeta-bit.pt/Conll_Coref_train#tense, http://www.ieeta-bit.pt/Conll_Coref_train#verbform]
    attributes: [lemma, word, wikidataId, chunk_tags, pos_tags]
  - name: sentence
    uri: http://www.ieeta-bit.pt/Conll_Coref_train#Sentence
#    edges_source: [sentence, sentence]
#    edges: [nextSentence, depGraph]
#    edges_target: [sentence, word]
#    edges_uri: [http://www.ieeta-bit.pt/Conll_Coref_train#nextSentence, http://www.ieeta-bit.pt/Conll_Coref_train#depGraph]
    edges_source: [sentence]
    edges: [nextSentence]
    edges_target: [sentence]
    edges_uri: [http://www.ieeta-bit.pt/Conll_Coref_train#nextSentence]
    attributes: [senttext]
target:
  - node: word
    name: [ner_tags]
    uri: [http://www.ieeta-bit.pt/Conll_Coref_train#ner_tags]
    balancing: False