connection:
  - connection_uri: http://hlt.ieeta.pt:8890/sparql
    graph_name: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#
    base_uri: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#
enable_wandb:
  True
nodes:
  - name: word
    uri: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#Word
    edges_source: [word, word, word, word, word, word]
    edges: [softwareMention, depGraph, head, previousWord, nextWord, fromSentence]
    edges_target: [Entity, word, word, word, word, sentence]
    edges_uri: [http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#softwareMention, http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#depGraph, http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#head, http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#previousWord, http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#fromSentence]
    attributes: [edge, lemma, pos, poscoarse, word, aspect, case, conjtype, definite, mood, degree, foreign, gender, number, numtype, person, polarity, poss, prontype, punctside, puncttype, tense, verbform]
  - name: sentence
    uri: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#Sentence
    edges_source: [sentence, sentence]
    edges: [nextSentence, previousSentence]
    edges_target: [sentence, sentence]
    edges_uri: [http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#nextSentence, http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#previousSentence]
    attributes: [senttext]
  - name: Entity
    uri: http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#Entity
    edges_source: []
    edges: []
    edges_target: []
    edges_uri: []
    attributes: [softwareMention_text]
target:
  - node: word
    name: [softwareMention]
    uri: [http://www.ieeta-bit.pt/Subtask1_LinkPrediction_v2#softwareMention]
    balancing: True