embeddings: True
epochs: 1500
batch_size: 32
validation_split: 0.3
test_split: 0.15
data_file: data/OpenIE/S2_2kTrain_Embeddings_FixedTarget.pt
targets_file: data/OpenIE/S2_5kTrain_Embeddings_FixedTarget.pkl
model_file: models/OpenIE/S2_5kTrain_Embeddings_FixedTarget.pt
test_data_file: data/OpenIE/S2_5kTest_Embeddings_FixedTarget.pt
test_targets_file: data/OpenIE/S2_5kTest_Embeddings_FixedTarget.pkl