epochs: 200
batch_size: 32
validation_split: 0.15
test_split: 0.2
data_file: data/GraphData/Track1/DataPropertiesBinaryModel_3000.pt
targets_file: data/GraphData/Track1/DataPropertiesBinaryModel_3000.pkl
model_file: models/Track1/gnn_first5k.pt
