epochs: 1500
batch_size: 32
validation_split: 0.3
test_split: 0.15
data_file: data/GraphData/Conll/Conll_2kTrain_9classes_NoEmbeddings.pt
targets_file: data/GraphData/Conll/Conll_2kTrain_9classes_NoEmbeddings.pkl
model_file: models/Conll_3kTrain_9classes_NoEmbeddings.pt
test_data_file: data/GraphData/Conll/Conll_1kTest_9classes_NoEmbeddings.pt
test_targets_file: data/GraphData/Conll/Conll_1kTest_9classes_NoEmbeddings.pkl